export const ERROR_CODE = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  RECRUITER_COMPANY_MISSING: 'RECRUITER_COMPANY_MISSING',
  INVALID_JOB_POSTING_STATUS: 'INVALID_JOB_POSTING_STATUS',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
