services:
  server:
    build:
      context: .
      dockerfile: local.dockerfile
    env_file: ./.env
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal

  db:
    image: postgres:18.3
    env_file: ./.env
    volumes:
      - career-scope-db-data:/var/lib/postgresql
    ports:
      - '${POSTGRES_HOST_PORT}:${POSTGRES_PORT}'
    networks:
      - internal

  redis:
    image: redis:alpine
    env_file: ./.env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - career-scope-redis-data:/data
    networks:
      - internal

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - '${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}'
    depends_on:
      - redis
    networks:
      - internal

volumes:
  career-scope-db-data:
  career-scope-redis-data:

networks:
  internal:
    driver: bridge
